import{parseSlip,toChatGPT,exportSlip}from"./parser.js";import{combinedOdds,potentialReturn,impliedProbability,gapText}from"./calculations.js";import{structuralChecks,summarize}from"./validator.js";import mock from"../adapters/sportybet-mock.js";import live from"../adapters/sportybet-live.js";import{loadState,saveState,loadHistory,addHistory,clearState}from"./storage.js";
const $=id=>document.getElementById(id);let state=loadState()||{slip:{version:3,slipName:"",targetOdds:30,stake:1000,bookmaker:"SportyBet Nigeria",selections:[]},mode:"live",debug:false};let results=[];let debugLog=[];
function ad(){return state.mode==="mock"?mock:live}function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}function money(n){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:2}).format(n)}function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
function msg(id,text,cls){$(id).textContent=text;$(id).className="message "+cls}
function persist(){saveState(state)}
function render(){ $("slipName").value=state.slip.slipName||"";$("target").value=state.slip.targetOdds??30;$("stake").value=state.slip.stake??1000;$("book").value=state.slip.bookmaker||"SportyBet Nigeria";$("modeSelect").value=state.mode;$("connectionState").textContent=state.mode==="mock"?"MOCK MODE":"LIVE MODE";const c=combinedOdds(state.slip.selections);$("count").textContent=state.slip.selections.length;$("odds").textContent=c.toFixed(2)+"×";$("ret").textContent=money(potentialReturn(state.slip.stake,c));$("prob").textContent=c>1?impliedProbability(c).toFixed(2)+"%":"—";msg("gap",state.slip.selections.length?gapText(c,Number(state.slip.targetOdds)||0):"Import a slip to begin.",c>=Number(state.slip.targetOdds||0)&&state.slip.selections.length?"ok":"neutral");renderResults();renderHistory();renderBooking();$("debugPanel").textContent=state.debug?JSON.stringify(debugLog,null,2):"Debug is hidden.";persist()}
function renderResults(){if(!results.length){$("results").innerHTML="<div class='empty'>Run CHECK SPORTYBET to resolve each selection.</div>";$("validationSummary").classList.add("hidden");$("buildBtn").disabled=true;return}$("results").innerHTML=results.map((r,i)=>{const s=r.selection||{},fail=!["MATCHED","ODDS_CHANGED"].includes(r.status),cur=r.currentOdds??r.liveOdds;const reason=r.reason||({NOT_FOUND:"Event was not found.",AMBIGUOUS:"Multiple close matches were found.",UNAVAILABLE:"Market or selection is unavailable.",SUSPENDED:"The selection is suspended.",STARTED:"The event has already started.",FAILED:"SportyBet request failed."}[r.status]||"Validation failed.");return"<div class='pick'><div class='pick-top'><div><div class='pick-title'>"+(i+1)+". "+esc(s.event)+"</div><div class='pick-sub'>"+esc(s.sport)+" · "+esc(s.market)+" · <b>"+esc(s.pick)+"</b></div></div><span class='status "+esc(r.status||"FAILED")+"'>"+esc((r.status||"FAILED").replace("_"," "))+"</span></div>"+(r.homeTeam?"<div class='pick-meta'>"+esc(r.homeTeam)+" vs "+esc(r.awayTeam)+"</div>":"")+"<div class='match-grid'><div><b>EVENT ID</b>"+esc(r.eventId||"—")+"</div><div><b>MARKET</b>"+esc(r.marketName||"—")+"</div><div><b>SELECTION</b>"+esc(r.outcomeName||s.pick||"—")+"</div><div><b>CURRENT ODDS</b>"+(cur?Number(cur).toFixed(2)+"×":"—")+"</div></div>"+(fail?"<div class='message bad'>"+esc(reason)+"</div><div class='failure-actions'><button class='secondary' data-remove='"+i+"'>REMOVE</button><button class='ghost' data-research='"+i+"'>RESEARCH REPLACEMENT</button></div>":"")+"</div>"}).join("");const sm=summarize(results);$("validationSummary").className="message "+(sm.ready?"ok":"bad");$("validationSummary").textContent=sm.ready?sm.total+" selections · "+sm.matched+" matched · ready to build.":sm.total+" selections · "+sm.matched+" matched · "+sm.failed+" failed."; $("buildBtn").disabled=!sm.ready}
function renderBooking(){const b=state.booking;if(!b){$("bookingEmpty").classList.remove("hidden");$("bookingResult").classList.add("hidden");return}$("bookingEmpty").classList.add("hidden");$("bookingResult").classList.remove("hidden");$("bookingResult").innerHTML="<div class='booking-box'><div class='pick-meta'>BOOKING CODE</div><div class='booking-code'>"+esc(b.bookingCode||"Unavailable")+"</div><div class='booking-actions'><button id='copyBooking' "+(b.bookingCode?"":"disabled")+">COPY CODE</button><button id='openBooking' "+(b.shareUrl?"":"disabled")+">OPEN SPORTYBET</button></div>"+(b.warning?"<div class='message warn'>"+esc(b.warning)+"</div>":"")+"</div>";if(b.bookingCode)$("copyBooking").onclick=async()=>{await navigator.clipboard.writeText(b.bookingCode);toast("Booking code copied.")};if(b.shareUrl)$("openBooking").onclick=()=>window.open(b.shareUrl,"_blank","noopener,noreferrer")}
function renderHistory(){const h=loadHistory();$("history").innerHTML=h.length?h.slice(0,12).map(x=>"<div class='history-row'><div><div class='history-code'>"+esc(x.bookingCode)+"</div><div class='history-meta'>"+esc(x.slipName||"Slip")+" · "+esc(x.created)+"</div></div><button class='ghost small' data-code='"+esc(x.bookingCode)+"'>COPY</button></div>").join(""):"<div class='empty'>No booking codes yet.</div>"} 
$("importBtn").onclick=()=>{try{state.slip=parseSlip($("importBox").value);results=[];state.booking=null;debugLog=[];msg("importMessage","Imported "+state.slip.selections.length+" selections.","ok");$("importMessage").classList.remove("hidden");render()}catch(e){msg("importMessage",e.message,"bad");$("importMessage").classList.remove("hidden")}};
$("pasteBtn").onclick=async()=>{try{$("importBox").value=await navigator.clipboard.readText();toast("Pasted.")}catch(e){toast("Paste permission blocked.")}};
$("demoBtn").onclick=()=>{const d={version:3,slipName:"30x Test Slip",targetOdds:30,stake:1000,bookmaker:"SportyBet Nigeria",selections:[{sport:"tennis",event:"Borna Gojo vs Maxi Carrascosa Diaz",market:"Match Winner",pick:"Borna Gojo",odds:1.04},{sport:"tennis",event:"Coco Gauff vs Xinran Sun",market:"Match Winner",pick:"Coco Gauff",odds:1.05},{sport:"tennis",event:"Kimmer Coppejans vs Nishesh Basavareddy",market:"Match Winner",pick:"Nishesh Basavareddy",odds:1.14},{sport:"football",event:"France vs Belgium",market:"Total Goals",pick:"Under 3.5",odds:1.44},{sport:"football",event:"Italy vs Türkiye",market:"Double Chance",pick:"Italy 1X",odds:1.12}]};$("importBox").value=toChatGPT(d);state.slip=d;results=[];state.booking=null;msg("importMessage","Loaded the supplied test slip.","info");$("importMessage").classList.remove("hidden");render()};
$("copyChatgptBtn").onclick=async()=>{await navigator.clipboard.writeText(toChatGPT(state.slip));toast("ChatGPT slip copied.")};$("copyJsonBtn").onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(exportSlip(state.slip),null,2));toast("JSON copied.")};
$("modeSelect").onchange=()=>{state.mode=$("modeSelect").value;results=[];state.booking=null;render()};
$("clearBtn").onclick=()=>{state.slip={version:3,slipName:"",targetOdds:30,stake:1000,bookmaker:"SportyBet Nigeria",selections:[]};results=[];state.booking=null;clearState();render()};
["slipName","target","stake","book"].forEach(id=>$(id).addEventListener("input",()=>{if(id==="slipName")state.slip.slipName=$(id).value;if(id==="target")state.slip.targetOdds=Number($(id).value)||0;if(id==="stake")state.slip.stake=Number($(id).value)||0;if(id==="book")state.slip.bookmaker=$(id).value;render()}));
$("validateBtn").onclick=async()=>{if(!state.slip.selections.length){msg("validationSummary","Import a slip first.","bad");$("validationSummary").classList.remove("hidden");return}const issues=structuralChecks(state.slip);if(issues.length){results=state.slip.selections.map((s,i)=>{const z=issues.find(x=>x.index===i)||issues.find(x=>x.index===-1);return{status:"FAILED",selection:s,reason:z?.message||"Slip validation failed."}});render();return}results=[];debugLog=[];state.booking=null;render();$("validateBtn").disabled=true;$("validateBtn").textContent="CHECKING…";for(let i=0;i<state.slip.selections.length;i++){const r=await ad().validateSelection(state.slip.selections[i],x=>debugLog.push({selection:i+1,...x}));results.push(r);renderResults()}$("validateBtn").disabled=false;$("validateBtn").textContent="CHECK SPORTYBET";persist();render()};
$("buildBtn").onclick=async()=>{const sm=summarize(results);if(!sm.ready)return;$("buildBtn").disabled=true;$("buildBtn").textContent="BUILDING…";try{const b=await ad().buildBooking(results,x=>debugLog.push(x));if(!b.success){state.booking={warning:b.message||"Booking creation failed."};}else{state.booking={bookingCode:b.bookingCode,shareUrl:b.shareUrl,created:new Date().toLocaleString("en-NG")};addHistory({bookingCode:b.bookingCode,shareUrl:b.shareUrl,slipName:state.slip.slipName,created:new Date().toLocaleString("en-NG")});toast("Booking code created.")}render()}catch(e){state.booking={warning:e.message==="CORS_OR_NETWORK"?"SportyBet blocked the browser request. GitHub Pages cannot proxy it server-side.":"Booking request failed: "+e.message};render()}$("buildBtn").disabled=false;$("buildBtn").textContent="BUILD BOOKING CODE";};
$("results").onclick=e=>{const rem=e.target.closest("[data-remove]");if(rem){state.slip.selections.splice(Number(rem.dataset.remove),1);results=[];state.booking=null;render()}const rr=e.target.closest("[data-research]");if(rr){const s=state.slip.selections[Number(rr.dataset.research)];$("importBox").value+="\nRESEARCH REPLACEMENT: "+s.sport+" | "+s.event+" | "+s.market+" | "+s.pick;toast("Replacement request added to import box.")}};
$("history").onclick=async e=>{const b=e.target.closest("[data-code]");if(b){await navigator.clipboard.writeText(b.dataset.code);toast("Copied.")}};
$("toggleDebugBtn").onclick=()=>{state.debug=!state.debug;$("debugPanel").textContent=state.debug?JSON.stringify(debugLog,null,2):"Debug is hidden.";persist()};$("copyDebugBtn").onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(debugLog,null,2));toast("Debug copied.")};
render();