const SPORT_IDS={football:"sr:sport:1",basketball:"sr:sport:2",tennis:"sr:sport:5",handball:"sr:sport:6",volleyball:"sr:sport:23",baseball:"sr:sport:3","ice hockey":"sr:sport:4"};
const STOP=new Set(["fc","cf","club","the","men","women","team","ac","sc"]);
function norm(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim()}
function toks(s){return norm(s).split(" ").filter(x=>x&&!STOP.has(x))}
function ov(a,b){const A=new Set(toks(a)),B=new Set(toks(b));if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(A.size,B.size)}
function sides(s){const p=String(s||"").split(/\s+(?:vs\.?|v\.?|versus)\s+|\s+[-–—]\s+/i);return p.length===2?p:["",s]}
export function eventScore(req,e){const [rh,ra]=sides(req);const direct=(ov(rh,e.homeTeamName)+ov(ra,e.awayTeamName))/2;const reverse=(ov(rh,e.awayTeamName)+ov(ra,e.homeTeamName))/2;return Math.max(direct,reverse*.97,ov(req,String(e.homeTeamName)+" vs "+String(e.awayTeamName))*.85)}
function marketScore(req,m,pick){const a=norm(req),b=norm(m);if(a===b)return 1;if(b.includes(a)||a.includes(b))return .88;const aliases={"match winner":["match winner","winner","moneyline"],"double chance":["double chance"],"total goals":["total goals","over under"],"both teams to score":["both teams to score","btts"],"draw no bet":["draw no bet","dnb"]};for(const k in aliases)if(aliases[k].some(v=>norm(v)===a)&&aliases[k].some(v=>b.includes(norm(v))))return .86;return 0}
function outcomeScore(req,d){const a=norm(req),b=norm(d);if(a===b)return 1;if(a&&b&&(b.includes(a)||a.includes(b)))return .9;return ov(a,b)}
export function chooseEvent(req,candidates){const r=candidates.map(e=>({...e,_score:eventScore(req,e)})).sort((a,b)=>b._score-a._score);if(!r.length||r[0]._score<.42)return{status:"NOT_FOUND",candidates:r.slice(0,3)};if(r[1]&&r[0]._score-r[1]._score<.06)return{status:"AMBIGUOUS",candidates:r.slice(0,3)};return{status:"FOUND",event:r[0]}}
function lineFromPick(p){const m=String(p||"").match(/(?:over|under|exactly|at least|below)?\s*(\d+(?:\.\d+)?)/i);return m?m[1]:null}\nexport function chooseMarket(req,markets,pick){const line=lineFromPick(pick);const r=(markets||[]).map(m=>{let score=marketScore(req,m.desc||m.name||"");const spec=String(m.specifier||"");if(line&&spec===line)score+=.12;else if(line&&norm(m.desc||"").includes(norm(line)))score+=.08;return{...m,_score:score}}).sort((a,b)=>b._score-a._score);if(!r[0]||r[0]._score<.55)return{status:"UNAVAILABLE",candidates:r.slice(0,4)};if(r[1]&&r[0]._score-r[1]._score<.05)return{status:"AMBIGUOUS",candidates:r.slice(0,4)};return{status:"FOUND",market:r[0]}}
export function chooseOutcome(req,outcomes){const r=(outcomes||[]).map(o=>({...o,_score:outcomeScore(req,o.desc||o.name||"")})).sort((a,b)=>b._score-a._score);if(!r[0]||r[0]._score<.55)return{status:"UNAVAILABLE",candidates:r.slice(0,5)};if(r[1]&&r[0]._score-r[1]._score<.04)return{status:"AMBIGUOUS",candidates:r.slice(0,5)};return{status:"FOUND",outcome:r[0]}}
export function sportId(s){return SPORT_IDS[s]||null}