const SPORTS={soccer:"football",football:"football",tennis:"tennis",basketball:"basketball",hoops:"basketball",handball:"handball",volleyball:"volleyball",hockey:"ice hockey","ice hockey":"ice hockey",baseball:"baseball"};
function quotes(s){return String(s||"").replace(/[“”„‟]/g,'"').replace(/[‘’‚‛]/g,"'").trim()}
function fences(s){return s.replace(/^\s*\`\`\`(?:json)?\s*/i,"").replace(/\s*\`\`\`\s*$/,"").trim()}
export function sportName(s){const x=String(s||"").toLowerCase().replace(/[^a-z ]/g,"").replace(/\s+/g," ").trim();return SPORTS[x]||x||"unknown"}
export function marketName(s){const x=String(s||"").toLowerCase().replace(/\s+/g," ").trim();if(["moneyline","winner","matchwinner","match win"].includes(x))return"match winner";if(["doublechance","1x","x2","12"].includes(x))return"double chance";if(["totals","goals total","over under","over/under","totalgoal"].includes(x))return"total goals";if(["btts","gg/ng","both teams to score"].includes(x))return"both teams to score";if(["dnb"].includes(x))return"draw no bet";return x}
function selection(s){return{sport:sportName(s.sport||s.sportName),event:String(s.event||s.match||s.fixture||"").trim(),market:marketName(s.market||s.marketName),pick:String(s.pick??s.selection??s.outcome??"").trim(),odds:Number(s.odds??s.price??s.multiplier??0)||0,startTime:String(s.startTime??s.start_time??s.kickoff??"").trim()}}
export function parseSlip(raw){const text=fences(quotes(raw));if(!text)throw Error("Paste a slip first.");if(text.startsWith("{"))return objectSlip(JSON.parse(text));return textSlip(text)}
function objectSlip(x){const arr=Array.isArray(x.selections)?x.selections:(Array.isArray(x.picks)?x.picks:[]);if(!arr.length)throw Error("I couldn't find any selections.");return{version:3,slipName:String(x.slipName||x.name||"Imported Slip"),targetOdds:Number(x.targetOdds??x.target_multiplier??x.targetMultiplier??30)||30,stake:Number(x.stake??x.amount??1000)||1000,bookmaker:String(x.bookmaker||"SportyBet Nigeria"),selections:arr.map(selection).filter(s=>s.event&&s.pick)}}
function textSlip(t){let bookmaker="SportyBet Nigeria",targetOdds=30,stake=1000,slipName="ChatGPT Slip";const selections=[];for(const raw of t.split(/\r?\n/)){const l=raw.trim();const u=l.toUpperCase();if(!l)continue;if(/^BOOKMAKER\s*=/.test(u)){bookmaker=l.split("=").slice(1).join("=").trim();continue}if(/^SLIP(NAME)?\s*=/.test(u)){slipName=l.split("=").slice(1).join("=").trim();continue}if(/^TARGET(_ODDS|_MULTIPLIER)?\s*=/.test(u)){targetOdds=Number(l.split("=").slice(1).join("=").trim())||targetOdds;continue}if(/^STAKE\s*=/.test(u)){stake=Number(l.split("=").slice(1).join("=").trim())||stake;continue}const p=l.split("|").map(x=>x.trim());if(p.length>=5&&/^\d+$/.test(p[0]))selections.push(selection({sport:p[1],event:p[2],market:p[3],pick:p[4],odds:p[5],startTime:p[6]}))}if(!selections.length)throw Error("No selections found. Use BETSLIP format or JSON.");return{version:3,slipName,targetOdds,stake,bookmaker,selections}}
export function toChatGPT(s){const a=["BETSLIP","BOOKMAKER="+(s.bookmaker||"SportyBet"),"TARGET="+Number(s.targetOdds||30)];if(Number(s.stake)>0)a.push("STAKE="+Number(s.stake));a.push("");(s.selections||[]).forEach((x,i)=>a.push((i+1)+" | "+x.sport+" | "+x.event+" | "+x.market+" | "+x.pick+" | "+Number(x.odds||0).toFixed(2)));return a.join("\n")}
export function exportSlip(s){return{version:3,slipName:s.slipName||"",targetOdds:Number(s.targetOdds||30),stake:Number(s.stake||0),bookmaker:s.bookmaker||"SportyBet Nigeria",selections:(s.selections||[]).map(x=>selection(x))}}